sudo: required
dist: trusty

before_install:
  - sudo integration-scripts/install_repositories.sh
install:
  - sudo integration-scripts/install_common.sh
  - sudo integration-scripts/install_codeface_R.sh
  - sudo integration-scripts/install_codeface_python.sh
  - sudo integration-scripts/install_cppstats.sh
  - sudo integration-scripts/setup_database.sh
  - integration-scripts/install_codeface_node.sh
script:
  - integration-scripts/test_codeface.sh
